### ISSUE TITLE
PHP CLI works, PHP-FPM is not working

### ISSUE THREAD

**Issue by ktamas77** [edamov/pushok#36]
Hello,

everything works fine from php command line, but php-fpm is not working (same code).
I'm using the provided docker image, and I added php-fpm7 to the Dockerfile
```
RUN apk add --update --no-cache \
        php7 \
        php7-fpm \
        php7-curl \
        php7-dom \
        php7-gmp \
        php7-intl \
        php7-json \
        php7-mbstring \
        php7-openssl \
        php7-phar \
        php7-xml \
        php7-xmlwriter
```

`phpinfo()` shows that i have all the required libraries installed in both CLI and FPM versions:

```
SSL Version | OpenSSL/1.0.2o
HTTP2 | Yes
cURL Information | 7.50.1
```

When i send a push from CLI, it arrives properly to the device.
However when I'm trying to send it through PHP-FPM, i'm getting this error.

```
server_1  | 2018/05/08 21:40:58 [error] 7#7: *34 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 1 in /var/www/api/vendor/edamov/pushok/src/Client.php on line 123
server_1  | PHP message: Slim Application Error:
server_1  | Type: TypeError
server_1  | Message: Argument 3 passed to Pushok\Response::__construct() must be of the type string, null given, called in /var/www/api/vendor/edamov/pushok/src/Client.php on line 125
server_1  | File: /var/www/api/vendor/edamov/pushok/src/Response.php
server_1  | Line: 144
server_1  | Trace: #0 /var/www/api/vendor/edamov/pushok/src/Client.php(125): Pushok\Response->__construct(0, '', NULL, 'a4a16383226d5a5...')
server_1  | #1 /var/www/api/templates/sendtest.phtml(53): Pushok\Client->push()
server_1  | #2 /var/www/api/vendor/slim/php-view/src/PhpRenderer.php(188): include('/var/www/api/te...')
server_1  | #3 /var/www/api/vendor/slim/php-view/src/PhpRenderer.php(169): Slim\Views\PhpRenderer->protectedIncludeScope('/var/www/api/sr...', Array)
server_1  | #4 /var/www/api/vendor/slim/php-view/src/PhpRenderer.php(62): Slim\Views\PhpRenderer->fetch('sendtest.phtml', Array)
server_1  | #5 /var/www/api/src/routes.php(8): Slim\Views\PhpRenderer->render(Object(Slim\Http\Response), 'sendtest.phtml', Array)
server_1  | #6 [internal function]: Closure->{closure}(Object(Slim\Http\Requ" while reading response header from upstream, client: 172.23.0.1, server: , request: "GET /test2 HTTP/1.1", upstream: "fastcgi://172.23.0.3:9000", host: "localhost"
```

any ideas / advices?
does it works for anyone with PHP-FPM?

**Comment by ktamas77** [comment]
Fixed this issue - PHP-FPM should run as root in the Alpine Linux distro.
